import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

//components
import Header from "./components/Header";
import MyApp from "./MyApp";

export const metadata = {
  title: "Åsa Norberg | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <MyApp>
          <Header />
          {children}
        </MyApp>
      </body>{" "}
    </html>
  );
}
